//! Backlog parity gates — replay divergence-lead ledgers from the prod jsonl
//! sinks (May–June 2026) against mainnet expectations captured at fixture time.
//!
//! Each test applies EVERY real tx of one ledger via `apply_ledger_in_order`
//! (LayeredProvider path, SLE state fetched from full-history s2 pinned at
//! seq-1) and asserts FULL parity with mainnet:
//!   - live_apply_diverged == 0          (no ter*/tef*/tem*/tel* from us)
//!   - live_apply_silent_diverged == 0   (our tes/tec TER == recorded TER)
//!   - live_apply_mutation_diverged == 0 (same AffectedNodes key/kind sets)
//!
//! Fixtures generated by `scripts/fetch_ledger_fixture.py <seq>`.
//! Leads (from /mnt/xrpl-data/{silent,mutation}_divergences.jsonl, captured
//! BEFORE the 6893bbe succ fix and the 2026-07-16 892a9dc succ-walk merge —
//! some may already be green; green = retired lead kept as regression cover):
//!   105035380  Payment tecPATH_PARTIAL vs tesSUCCESS
//!   105035381  Payment mutation mix (2 extra + 3 missing)
//!   105091578  recurring 3-key mutation swap across 5 txs + PATH silents
//!   105091579  OfferCreate tecKILLED vs tesSUCCESS
//!   105284279  NFTokenMint tecINVARIANT_FAILED "NFT found in incorrect page"
//!              + downstream NFTokenCreateOffer tecNO_ENTRY + five "+1 node" Payments
//!   105284280  OfferCreate mutation under-emission (5 vs 10)
//!
//! Network-dependent (SLE fetches + amendments from s2.ripple.com). Run:
//!   cargo test --features ffi --test backlog_reapply -- --ignored --nocapture

#![cfg(feature = "ffi")]

use std::collections::HashMap;

use xrpl_node::ffi_engine::{apply_ledger_in_order, fetch_mainnet_amendments, new_stats};

const RPC_URL: &str = "https://s2.ripple.com:51234";

fn hex_to_array32(s: &str) -> [u8; 32] {
    let v = hex::decode(s).expect("hex");
    let mut a = [0u8; 32];
    a.copy_from_slice(&v);
    a
}

fn parse_blobs(tsv: &str) -> Vec<Vec<u8>> {
    let mut rows: Vec<(u32, Vec<u8>)> = tsv
        .lines()
        .filter(|l| !l.is_empty())
        .filter_map(|l| {
            let mut p = l.splitn(2, '\t');
            let idx: u32 = p.next()?.parse().ok()?;
            Some((idx, hex::decode(p.next()?).ok()?))
        })
        .collect();
    rows.sort_by_key(|(i, _)| *i);
    rows.into_iter().map(|(_, b)| b).collect()
}

fn run_ledger(blobs_tsv: &str, expected_json: &str) {
    let exp: serde_json::Value = serde_json::from_str(expected_json).expect("expected json");
    let hdr = &exp["header"];
    let seq = hdr["ledger_seq"].as_u64().expect("seq") as u32;
    let parent_hash = hex_to_array32(hdr["parent_hash"].as_str().expect("parent"));
    let pct = hdr["parent_close_time"].as_u64().expect("pct") as u32;
    let drops = hdr["total_drops"].as_u64().expect("drops");

    let mut expected_outcomes: HashMap<String, String> = HashMap::new();
    let mut expected_mutations: HashMap<String, Vec<(String, u8)>> = HashMap::new();
    for (hash, v) in exp["txs"].as_object().expect("txs") {
        if let Some(ter) = v["ter"].as_str() {
            expected_outcomes.insert(hash.clone(), ter.to_string());
        }
        let nodes: Vec<(String, u8)> = v["nodes"]
            .as_array()
            .map(|a| {
                a.iter()
                    .filter_map(|n| {
                        Some((n[0].as_str()?.to_string(), n[1].as_u64()? as u8))
                    })
                    .collect()
            })
            .unwrap_or_default();
        if !nodes.is_empty() {
            expected_mutations.insert(hash.clone(), nodes);
        }
    }

    let txs = parse_blobs(blobs_tsv);
    assert!(!txs.is_empty(), "fixture has no txs");
    println!("Fetching mainnet amendments from {RPC_URL}…");
    let amendments = fetch_mainnet_amendments(RPC_URL);
    println!("Applying {} txs of #{seq} (expect full mainnet parity)…", txs.len());

    let stats = new_stats();
    let rpc_urls = vec![RPC_URL.to_string()];
    let _overlay = apply_ledger_in_order(
        &stats,
        &txs,
        seq,
        &rpc_urls,
        &amendments,
        parent_hash,
        pct,
        drops,
        None,
        None, // no snapshot -> LayeredProvider (overlay -> RPC pinned seq-1)
        None,
        Some(&expected_outcomes),
        None,
        Some(&expected_mutations),
    );

    let s = stats.lock();
    println!();
    println!("=== #{seq} parity result ===");
    println!("  attempted:          {}", s.live_apply_attempted);
    println!("  ok/claimed:         {}/{}", s.live_apply_ok, s.live_apply_claimed);
    println!("  diverged:           {}", s.live_apply_diverged);
    println!("  silent diverged:    {}", s.live_apply_silent_diverged);
    println!("  mutation diverged:  {}", s.live_apply_mutation_diverged);
    for x in &s.diverged_tx_samples {
        println!("    [ter ] {x}");
    }
    for x in &s.silent_diverged_samples {
        println!("    [tersilent] {x}");
    }
    for x in &s.mutation_diverged_samples {
        println!("    [muta] {x}");
    }

    assert_eq!(s.live_apply_attempted as usize, txs.len(), "every tx must be attempted");
    assert_eq!(s.live_apply_diverged, 0, "hard TER divergences");
    assert_eq!(s.live_apply_silent_diverged, 0, "silent TER mismatches vs mainnet");
    assert_eq!(s.live_apply_mutation_diverged, 0, "AffectedNodes set mismatches vs mainnet");
}

macro_rules! backlog_test {
    ($name:ident, $seq:literal) => {
        #[test]
        #[ignore = "network-dependent: fetches SLE state + amendments from s2.ripple.com"]
        fn $name() {
            run_ledger(
                include_str!(concat!("data/l", $seq, "_blobs.txt")),
                include_str!(concat!("data/l", $seq, "_expected.json")),
            );
        }
    };
}

backlog_test!(l105035380_replays_with_full_parity, 105035380);
backlog_test!(l105035381_replays_with_full_parity, 105035381);
backlog_test!(l105091578_replays_with_full_parity, 105091578);
backlog_test!(l105091579_replays_with_full_parity, 105091579);
backlog_test!(l105284279_replays_with_full_parity, 105284279);
backlog_test!(l105284280_replays_with_full_parity, 105284280);
